### ISSUE TITLE
Don't override the schema attribute maybd usefull while subclassing

### ISSUE THREAD

**Issue by tonthon** [Pylons/pyramid_deform#24]
I'd like to be able to dynamically build a FormView's schema using a property.

Since the following line try to override the schema attribute (https://github.com/Pylons/pyramid_deform/blob/master/pyramid_deform/__init__.py#L95)

``` python
self.schema = self.schema.bind(**self.get_bind_data())
```

that's not possible.

If an alternative attribute was used like 

``` python
self.bound_schema = self.schema.bind(**self.get_bind_data())
```

it would be ok for me.

**Comment by mcdonc** [comment]
You might be able to turn self.schema into a property?

**Comment by tonthon** [comment]
Sorry I forgot about implementing a setter.
